### ISSUE TITLE
Implement Settings page to menu item selection

### ISSUE THREAD

**Issue by zakirhere** [zakirhere/android-projects#3]
This is how it look when I replace the activity with such code:

```
    FragmentManager fragmentManager = getSupportFragmentManager();
    fragmentManager.beginTransaction()
            .replace(R.id.container, PlaceholderFragment.newInstance(position + 1))
            .commit();
```

![image](https://cloud.githubusercontent.com/assets/3741860/8892046/b11bc616-330f-11e5-8448-5f370a92d1ac.png)

**Comment by nasihere** [comment]
did you watch this video?
https://www.youtube.com/watch?v=xpU2SRYMlCU

**Comment by zakirhere** [comment]
Kuch samjha nahi. Can you implement if you could?

-Sent from phone

**Comment by dhavalhere** [comment]
Sure I will try Zakir

**Comment by zakirhere** [comment]
Not you Dhaval. Thats for nasir

-Sent from phone

**Comment by zakirhere** [comment]
This is resolved. Creating a new Activity and use Intent to switch between the class

**Comment by nasihere** [comment]
Nice...
